# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# 「and」「or」の使用を許可
AndOr:
  Enabled: false

# "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
Style/StringLiterals:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/PercentLiteralDelimiters:
    Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
    Enabled: false

Style/ExpandPathArguments:
    Enabled: false

Style/ClassMethods:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Style/MutableConstant:
  Enabled: false
    
#最後に新たな行を必要とする
TrailingBlankLines:
  EnforcedStyle: final_newline

AllCops:
  Exclude:
    - db/schema.rb
    - config/unicorn.rb
    - config/unicorn_staging.rb
    - tmp/**/*
    - Gemfile
    - bin/setup
    - Guardfile
    - bin/update
    - bin/rails
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/yarn
